#!/bin/bash

function checkFiles {
    dir=$1
    checkstyle_dir="$dir/config/checkstyle"
    jar_file="$checkstyle_dir/checkstyle.jar"
    config_file="$checkstyle_dir/ali_checkstyle.xml"
    files=$2
    is_err=0


    rm -f temp_git_check
    for file in $files ; do
        path="$dir/$file"
        if [ ! -f "$path" ]; then
          continue
        fi
        echo "check==> $path"
        (
        set -e
        java -jar $jar_file -c $config_file $path >> temp_git_check
        )
        errorCode=$?
        if [ $errorCode -ne 0 ];then
            is_err=-1
        fi
        warn=`cat temp_git_check | grep  "WARN"`
        if [[ $warn = *"WARN"* ]];then
            echo "$warn"
            is_err=-1
        fi

        err=`cat temp_git_check | grep  "ERROR"`
        if [[ $err = *"ERROR"* ]];then
             echo "$err"
             is_err=-1
        fi
    done
    rm -f temp_git_check
    return $is_err
}

change_files=`git status --porcelain | sed s/^...// | grep '\.java$'`
wd=`pwd`
checkFiles $wd $change_files
err=$?

if [ $err -ne  0 ];then
    echo ""
    echo "**************************"
    echo "  符合code style才能提交  "
    echo "**************************"
    exit -1
fi
#echo "Running ktlint"
#
#./gradlew ktlint
#result=$?
#if [ "$result" = 0 ] ; then
#   echo "ktlint found no problems"
#   exit 0
#else
#   echo ""
#   echo "**************************"
#   echo "  符合Kotlin style guide才能提交  "
#   echo "**************************"
#   exit 1
#fi
exit 0
